### ISSUE TITLE
Difference from Paper

### ISSUE THREAD

**Issue by nitrexcm** [dsecrieru/blueNoise#6]
The paper says
> While the active list is not empty, choose a random index from it (say _i_).

The code, however, always picks the _last_ active point:
https://github.com/dsecrieru/blueNoise/blob/764cbcb1d9694706bc68195197e922303606c70d/pds_Bridson.hpp#L105-L107

Is this deviation intended? It looks like taking away randomness. Or does the creation of neighbors in close proximity to the last point add enough randomness for it to work out?

**Comment by dsecrieru** [comment]
Hi!

Good catch!

If I remember correctly, it is an intended deviation. The reason was probably a gain in performance, without losing much. At least, I could not see any degradation in the quality of the distribution.

I did think about adding some kind of "quality evaluation", for example by plotting the distribution, so changes and further experimentation could be quantitatively assessed.

**Comment by nitrexcm** [comment]
Great, thanks! That answers my question :)
